add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
add_rules("mode.releasedbg")
set_languages("cxx26")
includes("deps/blook.lua")
add_requires("blook 79f84d4908290d86761cc28fe36bcf35c6115984", "cpptrace")

target("launcher")
    set_kind("binary")
    set_encodings("utf-8")
    add_ldflags("-subsystem:windows")
    add_files("src/*.cc", "src/resources.rc")
    add_defines("NOMINMAX")
    add_packages("blook", "cpptrace")
    set_policy("windows.manifest.uac", "admin")
    add_syslinks("user32")