add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
add_rules("mode.releasedbg")
set_languages("cxx26")
includes("deps/blook.lua")
add_requires("blook 6307435abeeb46d03507a33a244938dd2554dccf", "cpptrace")

target("launcher")
    set_kind("binary")
    add_rules("utils.bin2obj", {extensions = ".dll"})
    add_files("src/*.dll")
    set_encodings("utf-8")
    -- add_ldflags("-subsystem:windows")
    add_files("src/*.cc", "src/resources.rc")
    add_defines("NOMINMAX")
    add_packages("blook", "cpptrace")
    set_policy("windows.manifest.uac", "admin")
    add_syslinks("user32")